CREATE TABLE discounts (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  VALUE INTEGER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE posts (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE services (
  ID BIGINT NOT NULL,
  COST NUMERIC NOT NULL,
  DESCRIPTION VARCHAR(255),
  DURATION INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE discounts_id_seq START WITH 1;
CREATE SEQUENCE posts_id_seq START WITH 1;
CREATE SEQUENCE services_id_seq START WITH 1;