CREATE TABLE discounts (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  VALUE INTEGER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE posts (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE services (
  ID BIGINT NOT NULL,
  COST NUMERIC NOT NULL,
  DESCRIPTION VARCHAR(255),
  DURATION INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE passport (
  ID BIGINT NOT NULL,
  SERIES VARCHAR(255) DEFAULT '' NOT NULL,
  NUM VARCHAR(255) NOT NULL,
  ISSUED_BY VARCHAR(255) NOT NULL,
  ISSUE_DATE DATE NOT NULL,
  SUBDIVISION VARCHAR(255),
  COUNTRY VARCHAR(255) NOT NULL,
  BIND_BY VARCHAR(255),
  PRIMARY KEY (ID),
  UNIQUE (SERIES, NUM, BIND_BY)
);

CREATE TABLE address (
  ID BIGINT NOT NULL,
  COUNTRY VARCHAR(255) NOT NULL,
  DISTRICT VARCHAR(255),
  CITY VARCHAR(255) NOT NULL,
  STREET VARCHAR(255) NOT NULL,
  HOUSE VARCHAR(255) NOT NULL,
  SECTION VARCHAR(255),
  FLAT VARCHAR(255) NOT NULL,
  ZIP VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE contacts (
  ID BIGINT NOT NULL,
  PHONE VARCHAR(255),
  EMAIL VARCHAR(255),
  VK VARCHAR(255),
  SKYPE VARCHAR(255),
  FACEBOOK VARCHAR(255),
  TWITTER VARCHAR(255),
  ICQ VARCHAR(255),
  BIND_BY VARCHAR(255),
  PRIMARY KEY (ID),
  UNIQUE (PHONE, BIND_BY)
);

CREATE TABLE masters (
  ID BIGINT NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PATRONYMIC VARCHAR(255),
  BIRTH_DATE DATE NOT NULL,
  HIRING_DATE DATE NOT NULL,
  ID_PASSPORT INTEGER NOT NULL,
  ID_POST INTEGER NOT NULL,
  ID_REG_ADDRESS INTEGER NOT NULL,
  ID_LIVE_ADDRESS INTEGER,
  ID_CONTACT INTEGER NOT NULL,
  BUSY BOOLEAN,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PASSPORT) REFERENCES passport (ID),
  FOREIGN KEY (ID_POST) REFERENCES posts (ID),
  FOREIGN KEY (ID_REG_ADDRESS) REFERENCES address (ID),
  FOREIGN KEY (ID_LIVE_ADDRESS) REFERENCES address (ID),
  FOREIGN KEY (ID_CONTACT) REFERENCES contacts (ID)
);

CREATE SEQUENCE discounts_id_seq START WITH 1;
CREATE SEQUENCE posts_id_seq START WITH 1;
CREATE SEQUENCE services_id_seq START WITH 1;
CREATE SEQUENCE passport_id_seq START WITH 1;
CREATE SEQUENCE address_id_seq START WITH 1;
CREATE SEQUENCE contacts_id_seq START WITH 1;
CREATE SEQUENCE masters_id_seq START WITH 1;